### ISSUE TITLE
Wrong output pf the graphic plot of the internal dependencies

### ISSUE THREAD

**Issue by roelj** [radmedres/clmedview#37]
The output of the submitted and merged script gives:
![overview](https://cloud.githubusercontent.com/assets/1129198/9587673/027ee2c8-5024-11e5-834a-7315d4d2af6f.png)

In which libclutter and libgtk are not linked. However, the graphical user interface (GTK) shows up quite nicely.

The script I suggested has the following output:
![overview-roel](https://cloud.githubusercontent.com/assets/1129198/9587700/32cc96fa-5024-11e5-9610-b8037421f2f6.png)

Which I believe is correct.

**Comment by minovations** [comment]
I agree that your output is wright. The initial script does not work in our setting, so there is something wrong/different. But I don't get what is wrong, thats the the reason why I asked your help.
If this is hard for you, i will find some time to find out what is wrong and why it isn't working.

**Comment by roelj** [comment]
I think I don't understand the "initial script does not work" part. Does that mean the script didn't work on the first try? Or did the first version of the script didn't work?

I think some confusion comes from me sending multiple versions of the script. Sorry about that!

I pasted the version I created the above graphic with here:
https://gist.github.com/roelj/8b375cbc480105755892

If the problem is that my version of the script does not work for you at all, could you send the map file, so I can see where it goes wrong? Otherwise it's hard to debug.

**Comment by roelj** [comment]
We've built a working version of the script which will find its way in the radmedres:master soon (I think).
