### ISSUE TITLE
Window Width/level not working....

### ISSUE THREAD

**Issue by minovations** [radmedres/clmedview#5]
Hi Folks,

I started clmedview and loaded an image into memory. By clicking the right button, I wanted to change the window width and level settings. This is not possible!!!

By reading the source code, I understood how window width and level would working. The ww-wl request is not activated, because the "resources->ps_ActiveLayer" is NULL.

Could the "resources->ps_ActiveLayer" be set to the original image when loading the image?

Grts Jos

**Comment by roelj** [comment]
Yes, absolutely.

I think it would be great if the original layer could be selected in the sidebar by default as well. For this I'd like to propose this patch:
https://github.com/roelj/clmedview/commit/db40b89ed32c69f512e1dc878bfdcc7f2f74a04a

I can send send a pull request when this is what you'd like to see as well.

**Comment by minovations** [comment]
This seems to be what the viewer should do, do you create a pull request?
